name: Trigger Knowledge Base Workflow

on:
  push:
    branches:
    - main
jobs:
  trigger-repo2:
    runs-on: ubuntu-latest

    steps:
      - name: Send repository_dispatch event to Knowledge Base 
        uses: peter-evans/repository_dispatch@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: prcsmae/mkdocs-practice
          event-type: docs-updated
